mysite/app/urls.py
from django.urls import path

from app.views import (
    ProductDeleteView,  # ProductListView,
    ProductDetailView,
    PaymentSuccessView, PaymentFailedView,
    add_item, index,
    update_item, create_checkout_session)

app_name = "app"

urlpatterns = [
    # http://127.0.0.1:8000/
    path("", index, name='index'),
    # path("", ProductListView.as_view(), name="index"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("add_item/", add_item, name="add_item"),
    path("update_item/<int:my_id>/", update_item, name="update_item"),
    path("delete_item/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("failed/", PaymentFailedView.as_view(), name="failed"),
    path("api/checkout-session/<int:id>/", create_checkout_session, name="api_checkout_session"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app_name')),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    # http://127.0.0.1:8000/users/
    path("register/", views.register, name="register"),
    path("login/", LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("seller_profile/<int:id>/", views.seller_profile, name="seller_profile"),
]

mysite/app/templates/app/add_item.html
{% extends "app/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4 ">

            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
                placeholder="Enter item name..." name="name" id="name">

            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
                placeholder="Enter item price..." name="price" id="price">

            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
                placeholder="Enter item description..." name="description" id="description">

            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="upload">Upload Item Image</label>
            <input class="block mt-2" type="file" accept="image/*" name="upload" id="upload">

            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">
                Add Item
            </button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/app/templates/app/base.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <title>Online Store Hub</title>
</head>

<body>
    {% include "app/navbar.html" %}
    {% block content %}{% endblock content %}
</body>

</html>

mysite/app/templates/app/delete_item.html
{% extends "app/base.html" %}

{% block content %}
<h1 class="text-2xl m-10 font bold">Delete Product</h1>
<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray text-sm font mb-2">Are you sure you want to delete this item</label>
        <label class="block text-gray text-sm font mb-2">{{ item.name}}</label>
        <img class="w-40 h-40" src="{{ item.image.url}}" alt="image" srcset="">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'app:index' %}">Cancel</a>
</form>
{% endblock content %}

mysite/app/templates/app/detail.html
{% extends "app/base.html" %}

{% load humanize %}

{% block content %}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{ item.image.url }}" alt="images">
    <div class="w-2/3 text-xl ml-10 mt-5">
        <p class="mt-5">{{ item.name }}</p>
        <p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
        <p class="mt-5 text-gray-600">{{ item.description }}</p>
        <p class="mt-5 text-gray-600">
            <a href="{% url 'users:seller_profile' item.seller.id %}">@{{ item.seller }}</a>
        </p>
        <p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>
        <button class="bg-green-500 text-white mt-[50px]">
            <a href="{% url 'app:update_item' item.id %}">Update Item</a>
        </button>
        <button class="bg-red-500 text-white mt-[50px]">
            <a href="{% url 'app:delete_item' item.id %}">Delete Item</a>
        </button>
        <button class="bg-green-500 text-white mt-[50px]" id="checkout">
            Checkout
        </button>
    </div>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout');

    checkoutButton.addEventListener('click', function () {

        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch("{% url 'app:api_checkout_session' id=item.id %}", {
            method: 'POST',
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>
{% endblock content %}

mysite/app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Exclusive products</span>
            <span class="block xl:inline text-green-500">At Super Prices</span>
        </h1>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            You can order from anywhere in the world. Shipping is included
        </p>
    </div>

    <div class="mt-5 flex justify-center items-center">
        <h2 class="text-2xl font-bold mb-4">Search: </h2>
        <form class="flex">
            <input type="text" name="search" class="border rounded-l py-2 px-4 focus:outline-none focus:border-green-500">
            <button type="submit"
                class="bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded-r transition-transform transform hover:scale-105 ease-in-out duration-300">
                Search<span class="ml-2 animate-bounce"></span>
            </button>

        </form>
    </div>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-5">
        {% for item in page_obj %}
            <a href="{% url 'app:detail' item.id %}">
                <div class=" rounded overflow-hidden shadow-lg">
                    <img class="w-full h-[400px]" src="{{item.image.url}}" alt="images">
                    <div class="px-6 py-4">
                        <p class="font-bold text-xl mb-2">{{item.name}}</p>
                        <p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
                        <p class="font-bold text-xl text-indogo-500 mb-2">by: {{item.seller}}</p>
                        <p class="text-gray-700 text-base">{{ item.description}}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <div class="flex items-center justify-between space-x-2">
        <span class="space-x-2">
            {% if page_obj.has_previous %}
            <a href="?page=1" class="hover:text-gray-500">First</a>
            <a href="?page={{ page_obj.previous_page_number}}" class="hover:text-gray-500">Previous</a>
            {% endif %}
        </span>
    
        <span class="font-bold">
            {{ page_obj }}
        </span>
    
        <span class="space-x-2">
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number}}" class="hover:text-gray-500">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages}}" class="hover:text-gray-500">Last</a>
            {% endif %}
        </span>
    </div>

</main>
{% endblock content %}

mysite/app/templates/app/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div>
                    <a href="{% url 'app:index' %}" class="flex items-center px-2 py-4">
                        <img class="h-8 w-8" src="{% static 'app/images/shop.png' %}" alt="logo" />
                        <span class="text-gray-500 font-semibold text-xl">Online Store Hub</span>
                    </a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="{% url 'app:index' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                    <a href="{% url 'app:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
                    {% if user.is_authenticated %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                    {% else %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

mysite/app/templates/app/payment_failed.html
{% extends "app/base.html" %}

{% block content %}
    <p>Payment failed</p>
{% endblock content %}

mysite/app/templates/app/payment_success.html
{% extends "app/base.html" %}

{% block content %}
    <p>You have successfully paid</p>
{% endblock content %}

mysite/app/templates/app/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you want to delete {{ object }}</p>
    <input type="submit" value="Delete">
</form>

mysite/app/templates/app/update_item.html
{% extends "app/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600">Update New Item</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}"
                type="text" placeholder="Name..." name="name" id="name">

            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.price }}"
                type="text" placeholder="Price..." name="price" id="price">

            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
                value="{{ item.description }}" type="text" placeholder="Description..." name="description"
                id="description">

            <img class="w-20 h-20" src="{{ item.image.url }}" alt="image" srcset="">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="upload">Upload Image</label>
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">

            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">
                Update Item
            </button>
        </div>
    </form>
</div>

{% endblock content %}